---
- name: Render cloud-config template
  hosts: localhost
  gather_facts: no
  # vars_files:
  #   - vars.yaml

  tasks:
    - name: Render cloud-config template
      template:
        src: ../templates/cloud-config.j2
        dest: rendered-cloud-config.yaml

